steps:
  # Download maven cache
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: bash
    args:
      - '-c'
      - |
        gsutil cp gs://$_M2_CACHE/maven-graalvm.tar .
        if [ -f "maven-graalvm.tar" ]; then
            tar -xf maven-graalvm.tar -C /root/.m2
            rm maven-graalvm.tar
        fi

  # Build the sample images
  - name: ghcr.io/graalvm/graalvm-ce:java11-21.1.0
    entrypoint: bash
    args: ['./.cloudbuild/graal-build-script.sh']

  # Reupload maven cache to bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: bash
    args:
      - '-c'
      - |
        tar -cf maven-graalvm.tar -C /root/.m2 .
        gsutil cp maven-graalvm.tar gs://$_M2_CACHE

  # Start emulators
  - name: 'gcr.io/cloud-builders/docker'
    id: spanner-emulator
    args: ['run', '-d', '--network=cloudbuild', '--name=spanner-emulator', '-p', '9010:9010', '-p', '9020:9020', 'gcr.io/cloud-spanner-emulator/emulator:1.1.1']
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    id: firestore-emulator
    args: ['run', '-d', '--network=cloudbuild', '--name=firestore-emulator', 'google/cloud-sdk', 'sh', '-c', 'gcloud beta emulators firestore start --host-port=0.0.0.0:9010']
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    id: bigtable-emulator
    args: ['run', '-d', '--network=cloudbuild', '--name=bigtable-emulator', 'google/cloud-sdk', 'sh', '-c', 'gcloud beta emulators bigtable start --host-port=0.0.0.0:9010']
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    id: datastore-emulator
    args: ['run', '-d', '--network=cloudbuild', '--name=datastore-emulator', 'google/cloud-sdk', 'sh', '-c', 'gcloud beta emulators datastore start --host-port=0.0.0.0:9010']
    waitFor: ['-']
  # Wait for emulators to start
  - name: jwilder/dockerize:0.6.1
    args: ['dockerize', '-timeout=40s', '-wait=tcp://spanner-emulator:9010', '-wait=tcp://firestore-emulator:9010', '-wait=tcp://bigtable-emulator:9010', '-wait=tcp://datastore-emulator:9010']
    waitFor: [spanner-emulator, firestore-emulator, datastore-emulator, bigtable-emulator]

  # Run the tests
  - name: ghcr.io/graalvm/graalvm-ce:java11-21.1.0
    args: [ './google-cloud-graalvm-samples/graalvm-samples-client-library/bigquery-sample/target/com.example.bigquerysampleapplication' ]

  - name: ghcr.io/graalvm/graalvm-ce:java11-21.1.0
    args: [
        './google-cloud-graalvm-samples/graalvm-samples-client-library/cloud-sql-sample/target/com.example.cloudsqlsampleapplication',
        '-Dinstance=cloud-graalvm-support-ci:us-east1:test-instance',
        '-Dpassword=root'
    ]

  - name: ghcr.io/graalvm/graalvm-ce:java11-21.1.0
    args: [ './google-cloud-graalvm-samples/graalvm-samples-client-library/pubsub-sample/target/com.example.pubsubsampleapplication' ]

  - name: ghcr.io/graalvm/graalvm-ce:java11-21.1.0
    args: [ './google-cloud-graalvm-samples/graalvm-samples-client-library/storage-sample/target/com.example.storagesampleapplication' ]

  - name: ghcr.io/graalvm/graalvm-ce:java11-21.1.0
    args: [ './google-cloud-graalvm-samples/graalvm-samples-client-library/logging-sample/target/com.example.loggingsampleapplication' ]

  - name: ghcr.io/graalvm/graalvm-ce:java11-21.1.0
    args: [ './google-cloud-graalvm-samples/graalvm-samples-client-library/secretmanager-sample/target/com.example.secretmanagersampleapplication' ]

  - name: ghcr.io/graalvm/graalvm-ce:java11-21.1.0
    args: [ './google-cloud-graalvm-samples/graalvm-samples-client-library/tasks-sample/target/com.example.taskssampleapplication' ]

  - name: ghcr.io/graalvm/graalvm-ce:java11-21.1.0
    args: [ './google-cloud-graalvm-samples/graalvm-samples-client-library/trace-sample/target/com.example.tracesampleapplication' ]

  - name: ghcr.io/graalvm/graalvm-ce:java11-21.1.0
    args: [ './google-cloud-graalvm-samples/graalvm-samples-client-library/firestore-sample/target/com.example.firestoresampleapplication' ]
    env:
      - 'FIRESTORE_EMULATOR_HOST=firestore-emulator:9010'

  - name: ghcr.io/graalvm/graalvm-ce:java11-21.1.0
    args: [ './google-cloud-graalvm-samples/graalvm-samples-client-library/spanner-sample/target/com.example.spannersampleapplication' ]
    env:
      - 'SPANNER_EMULATOR_HOST=spanner-emulator:9010'

  - name: ghcr.io/graalvm/graalvm-ce:java11-21.1.0
    args: [ './google-cloud-graalvm-samples/graalvm-samples-client-library/bigtable-sample/target/com.example.bigtablesampleapplication' ]
    env:
      - 'BIGTABLE_EMULATOR_HOST=bigtable-emulator:9010'

  - name: ghcr.io/graalvm/graalvm-ce:java11-21.1.0
    args: [ './google-cloud-graalvm-samples/graalvm-samples-client-library/datastore-sample/target/com.example.datastoresampleapplication' ]
    env:
      - 'DATASTORE_EMULATOR_HOST=http://datastore-emulator:9010'

timeout: 3600s # 60 minutes
options:
  # Need to specify a better machine to avoid OOM errors.
  machineType: 'E2_HIGHCPU_32'
  volumes:
    - name: 'm2-cache'
      path: /root/.m2

substitutions:
  # Google Cloud Bucket containing the Maven cache.
  _M2_CACHE: 'graalvm-build-cache'

